<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-25T17:25:17 IST" name="Default suite" finished-at="2024-11-25T17:25:39 IST" duration-ms="22303">
    <groups>
    </groups>
    <test started-at="2024-11-25T17:25:17 IST" name="Default test" finished-at="2024-11-25T17:25:39 IST" duration-ms="22303">
      <class name="Navigation">
        <test-method signature="start()[pri:0, instance:Navigation@bf1ec20]" started-at="2024-11-25T17:25:17 IST" name="start" finished-at="2024-11-25T17:25:19 IST" duration-ms="1974" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method signature="getCalc()[pri:0, instance:Navigation@bf1ec20]" started-at="2024-11-25T17:25:19 IST" name="getCalc" finished-at="2024-11-25T17:25:38 IST" depends-on-methods="Navigation.start" duration-ms="19325" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getCalc -->
        <test-method signature="listCheck()[pri:0, instance:Navigation@bf1ec20]" started-at="2024-11-25T17:25:38 IST" name="listCheck" finished-at="2024-11-25T17:25:39 IST" depends-on-methods="Navigation.getCalc" duration-ms="950" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [110700] but found [$110700]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [110700] but found [$110700]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Navigation.listCheck(Navigation.java:112)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- listCheck -->
      </class> <!-- Navigation -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
